tls:
  certificates:
    - certFile: /etc/traefik/acme/traefik.crt
      keyFile: /etc/traefik/acme/traefik.key
  options:
    mintls13:
      minVersion: VersionTLS13
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

http:
  middlewares:
      local-plugin:
        plugin:
          auth:
            headers:
              Foo: Bar