name: Scheduled Release

on:
  workflow_dispatch:

jobs:
  scheduled-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - name: Get Previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@0.2.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Get next minor version
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1.0"
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      - name: manifest Version
        uses: deef0000dragon1/json-edit-action/@v1
        env:
          KEY: scheduleVersion
          VALUE: ${{ steps.semvers.outputs.patch }}
          FILE: package.json
      - uses: stefanzweifel/git-auto-commit-action@v4.6.0
        with:
          commit_message: 'fix(release): schedule release'