name: Scheduled Release

on:
  workflow_dispatch:

jobs:
  scheduled-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # renovate: tag=v2.3.5
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - name: Get Previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@1.0.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Get next minor version
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      - name: manifest Version
        uses: deef0000dragon1/json-edit-action@cb3f7455e89d659879ab7e4a55cbc9b10c36a713 # renovate: tag=v1
        env:
          KEY: scheduleVersion
          VALUE: ${{ steps.semvers.outputs.patch }}
          FILE: package.json
      - uses: stefanzweifel/git-auto-commit-action@abd87b7d94702070bef78dc1d56b6928b8fa9ecc # renovate: tag=v4.12.0
        with:
          commit_message: 'fix(release): schedule release'